var headhtml = ['<meta charset="UTF-8">',
'<meta http-equiv="X-UA-Compatible" content="IE=edge">',
'<meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">',
'<link rel="stylesheet" href="/study/statics/css/bootstrap.min.css">',
'<link rel="stylesheet" href="/study/statics/css/font-awesome.min.css">',
'<link rel="stylesheet" href="/study/statics/plugins/jqgrid/ui.jqgrid-bootstrap.css">',
'<link rel="stylesheet" href="/study/statics/plugins/ztree/css/metroStyle/metroStyle.css">',
'<link rel="stylesheet" href="/study/static/css/pictureViewer.css">',
'<link rel="stylesheet" href="/study/statics/css/main.css">',
'<link rel="stylesheet" href="/study/statics/css/iview.css">',
'<link rel="stylesheet" href="/study/statics/css/style.css">',
'<link rel="stylesheet" href="/study/statics/css/index.css">',
'<link rel="stylesheet" href="/study/statics/plugins/treegrid/jquery.treegrid.css">',
'<link rel="stylesheet" href="/study/statics/plugins/froala_editor/css/froala_editor.min.css"/>',
'<script src="/study/statics/libs/jquery.min.js"></script>',
'<script src="/study/statics/plugins/layer/layer.js"></script>',
'<script src="/study/statics/libs/bootstrap.min.js"></script>',
'<script src="/study/statics/libs/vue.min.js"></script>',
'<script src="/study/statics/libs/iview.min.js"></script>',
'<script src="/study/statics/plugins/jqgrid/grid.locale-cn.js"></script>',
'<script src="/study/statics/plugins/jqgrid/jquery.jqGrid.min.js"></script>',
'<script src="/study/statics/plugins/ztree/jquery.ztree.all.min.js"></script>',
'<script src="/study/statics/plugins/treegrid/jquery.treegrid.extension.js"></script>',
'<script src="/study/statics/plugins/treegrid/jquery.treegrid.min.js"></script>',
'<script src="/study/statics/plugins/treegrid/jquery.treegrid.bootstrap3.js"></script>',
'<script src="/study/statics/plugins/treegrid/tree.table.js"></script>',
'<script src="/study/statics/plugins/froala_editor/js/froala_editor.min.js"></script>',
'<script src="/study/statics/plugins/froala_editor/js/froala_editor_ie8.min.js"></script>',
'<script src="/study/statics/plugins/froala_editor/js/plugins/tables.min.js"></script>',
'<script src="/study/statics/plugins/froala_editor/js/plugins/lists.min.js"></script>',
'<script src="/study/statics/plugins/froala_editor/js/plugins/colors.min.js"></script>',
'<script src="/study/statics/plugins/froala_editor/js/plugins/media_manager.min.js"></script>',
'<script src="/study/statics/plugins/froala_editor/js/plugins/font_family.min.js"></script>',
'<script src="/study/statics/plugins/froala_editor/js/plugins/font_size.min.js"></script>',
'<script src="/study/statics/plugins/froala_editor/js/plugins/block_styles.min.js"></script>',
'<script src="/study/statics/plugins/froala_editor/js/plugins/video.min.js"></script>',
'<script src="/study/statics/plugins/froala_editor/js/langs/zh_cn.js"></script>',
'<script src="/study/statics/libs/jquery-extend.js"></script>',
'<script src="/study/statics/libs/iNotify.js"></script>',
'<script src="/study/static/js/jquery.mousewheel.min.js"></script>',
'<script src="/study/static/js/pictureViewer.js"></script>'].join('');
document.write(headhtml);