package com.study.model;

public class Orders {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.oid
     *
     * @mbggenerated
     */
    private Integer oid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.cpid
     *
     * @mbggenerated
     */
    private Integer cpid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.bid
     *
     * @mbggenerated
     */
    private Integer bid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.ocid
     *
     * @mbggenerated
     */
    private Integer ocid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.ocode
     *
     * @mbggenerated
     */
    private String ocode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.ophoto
     *
     * @mbggenerated
     */
    private String ophoto;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.mlast
     *
     * @mbggenerated
     */
    private String mlast;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.etd
     *
     * @mbggenerated
     */
    private String etd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.fsize
     *
     * @mbggenerated
     */
    private String fsize;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.onumber
     *
     * @mbggenerated
     */
    private String onumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.fafactory
     *
     * @mbggenerated
     */
    private String fafactory;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.exfactory
     *
     * @mbggenerated
     */
    private String exfactory;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.sfactory
     *
     * @mbggenerated
     */
    private String sfactory;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.bfactory
     *
     * @mbggenerated
     */
    private String bfactory;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.inid
     *
     * @mbggenerated
     */
    private Integer inid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.ouid
     *
     * @mbggenerated
     */
    private Integer ouid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.laid
     *
     * @mbggenerated
     */
    private Integer laid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.prid
     *
     * @mbggenerated
     */
    private Integer prid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.ofid
     *
     * @mbggenerated
     */
    private Integer ofid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.said
     *
     * @mbggenerated
     */
    private Integer said;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.tuid
     *
     * @mbggenerated
     */
    private Integer tuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.bcid
     *
     * @mbggenerated
     */
    private Integer bcid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.fsid
     *
     * @mbggenerated
     */
    private Integer fsid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.csid
     *
     * @mbggenerated
     */
    private Integer csid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.psid
     *
     * @mbggenerated
     */
    private Integer psid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.piid
     *
     * @mbggenerated
     */
    private Integer piid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.faid
     *
     * @mbggenerated
     */
    private Integer faid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.acid
     *
     * @mbggenerated
     */
    private Integer acid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.heid
     *
     * @mbggenerated
     */
    private Integer heid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.outid
     *
     * @mbggenerated
     */
    private Integer outid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.miid
     *
     * @mbggenerated
     */
    private Integer miid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.toid
     *
     * @mbggenerated
     */
    private Integer toid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.slid
     *
     * @mbggenerated
     */
    private Integer slid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.fpid
     *
     * @mbggenerated
     */
    private Integer fpid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.bpid
     *
     * @mbggenerated
     */
    private Integer bpid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.chid
     *
     * @mbggenerated
     */
    private Integer chid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.fmid
     *
     * @mbggenerated
     */
    private Integer fmid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.boid
     *
     * @mbggenerated
     */
    private Integer boid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.bkid
     *
     * @mbggenerated
     */
    private Integer bkid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.mkid
     *
     * @mbggenerated
     */
    private Integer mkid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.cuid
     *
     * @mbggenerated
     */
    private Integer cuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.ncid
     *
     * @mbggenerated
     */
    private Integer ncid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.shid
     *
     * @mbggenerated
     */
    private Integer shid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.paid
     *
     * @mbggenerated
     */
    private Integer paid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.exid
     *
     * @mbggenerated
     */
    private Integer exid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.payid
     *
     * @mbggenerated
     */
    private Integer payid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.shiid
     *
     * @mbggenerated
     */
    private Integer shiid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.oid
     *
     * @return the value of orders.oid
     *
     * @mbggenerated
     */
    public Integer getOid() {
        return oid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.oid
     *
     * @param oid the value for orders.oid
     *
     * @mbggenerated
     */
    public void setOid(Integer oid) {
        this.oid = oid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.cpid
     *
     * @return the value of orders.cpid
     *
     * @mbggenerated
     */
    public Integer getCpid() {
        return cpid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.cpid
     *
     * @param cpid the value for orders.cpid
     *
     * @mbggenerated
     */
    public void setCpid(Integer cpid) {
        this.cpid = cpid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.bid
     *
     * @return the value of orders.bid
     *
     * @mbggenerated
     */
    public Integer getBid() {
        return bid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.bid
     *
     * @param bid the value for orders.bid
     *
     * @mbggenerated
     */
    public void setBid(Integer bid) {
        this.bid = bid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.ocid
     *
     * @return the value of orders.ocid
     *
     * @mbggenerated
     */
    public Integer getOcid() {
        return ocid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.ocid
     *
     * @param ocid the value for orders.ocid
     *
     * @mbggenerated
     */
    public void setOcid(Integer ocid) {
        this.ocid = ocid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.ocode
     *
     * @return the value of orders.ocode
     *
     * @mbggenerated
     */
    public String getOcode() {
        return ocode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.ocode
     *
     * @param ocode the value for orders.ocode
     *
     * @mbggenerated
     */
    public void setOcode(String ocode) {
        this.ocode = ocode == null ? null : ocode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.ophoto
     *
     * @return the value of orders.ophoto
     *
     * @mbggenerated
     */
    public String getOphoto() {
        return ophoto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.ophoto
     *
     * @param ophoto the value for orders.ophoto
     *
     * @mbggenerated
     */
    public void setOphoto(String ophoto) {
        this.ophoto = ophoto == null ? null : ophoto.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.mlast
     *
     * @return the value of orders.mlast
     *
     * @mbggenerated
     */
    public String getMlast() {
        return mlast;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.mlast
     *
     * @param mlast the value for orders.mlast
     *
     * @mbggenerated
     */
    public void setMlast(String mlast) {
        this.mlast = mlast == null ? null : mlast.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.etd
     *
     * @return the value of orders.etd
     *
     * @mbggenerated
     */
    public String getEtd() {
        return etd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.etd
     *
     * @param etd the value for orders.etd
     *
     * @mbggenerated
     */
    public void setEtd(String etd) {
        this.etd = etd == null ? null : etd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.fsize
     *
     * @return the value of orders.fsize
     *
     * @mbggenerated
     */
    public String getFsize() {
        return fsize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.fsize
     *
     * @param fsize the value for orders.fsize
     *
     * @mbggenerated
     */
    public void setFsize(String fsize) {
        this.fsize = fsize == null ? null : fsize.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.onumber
     *
     * @return the value of orders.onumber
     *
     * @mbggenerated
     */
    public String getOnumber() {
        return onumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.onumber
     *
     * @param onumber the value for orders.onumber
     *
     * @mbggenerated
     */
    public void setOnumber(String onumber) {
        this.onumber = onumber == null ? null : onumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.fafactory
     *
     * @return the value of orders.fafactory
     *
     * @mbggenerated
     */
    public String getFafactory() {
        return fafactory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.fafactory
     *
     * @param fafactory the value for orders.fafactory
     *
     * @mbggenerated
     */
    public void setFafactory(String fafactory) {
        this.fafactory = fafactory == null ? null : fafactory.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.exfactory
     *
     * @return the value of orders.exfactory
     *
     * @mbggenerated
     */
    public String getExfactory() {
        return exfactory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.exfactory
     *
     * @param exfactory the value for orders.exfactory
     *
     * @mbggenerated
     */
    public void setExfactory(String exfactory) {
        this.exfactory = exfactory == null ? null : exfactory.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.sfactory
     *
     * @return the value of orders.sfactory
     *
     * @mbggenerated
     */
    public String getSfactory() {
        return sfactory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.sfactory
     *
     * @param sfactory the value for orders.sfactory
     *
     * @mbggenerated
     */
    public void setSfactory(String sfactory) {
        this.sfactory = sfactory == null ? null : sfactory.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.bfactory
     *
     * @return the value of orders.bfactory
     *
     * @mbggenerated
     */
    public String getBfactory() {
        return bfactory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.bfactory
     *
     * @param bfactory the value for orders.bfactory
     *
     * @mbggenerated
     */
    public void setBfactory(String bfactory) {
        this.bfactory = bfactory == null ? null : bfactory.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.inid
     *
     * @return the value of orders.inid
     *
     * @mbggenerated
     */
    public Integer getInid() {
        return inid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.inid
     *
     * @param inid the value for orders.inid
     *
     * @mbggenerated
     */
    public void setInid(Integer inid) {
        this.inid = inid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.ouid
     *
     * @return the value of orders.ouid
     *
     * @mbggenerated
     */
    public Integer getOuid() {
        return ouid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.ouid
     *
     * @param ouid the value for orders.ouid
     *
     * @mbggenerated
     */
    public void setOuid(Integer ouid) {
        this.ouid = ouid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.laid
     *
     * @return the value of orders.laid
     *
     * @mbggenerated
     */
    public Integer getLaid() {
        return laid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.laid
     *
     * @param laid the value for orders.laid
     *
     * @mbggenerated
     */
    public void setLaid(Integer laid) {
        this.laid = laid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.prid
     *
     * @return the value of orders.prid
     *
     * @mbggenerated
     */
    public Integer getPrid() {
        return prid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.prid
     *
     * @param prid the value for orders.prid
     *
     * @mbggenerated
     */
    public void setPrid(Integer prid) {
        this.prid = prid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.ofid
     *
     * @return the value of orders.ofid
     *
     * @mbggenerated
     */
    public Integer getOfid() {
        return ofid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.ofid
     *
     * @param ofid the value for orders.ofid
     *
     * @mbggenerated
     */
    public void setOfid(Integer ofid) {
        this.ofid = ofid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.said
     *
     * @return the value of orders.said
     *
     * @mbggenerated
     */
    public Integer getSaid() {
        return said;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.said
     *
     * @param said the value for orders.said
     *
     * @mbggenerated
     */
    public void setSaid(Integer said) {
        this.said = said;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.tuid
     *
     * @return the value of orders.tuid
     *
     * @mbggenerated
     */
    public Integer getTuid() {
        return tuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.tuid
     *
     * @param tuid the value for orders.tuid
     *
     * @mbggenerated
     */
    public void setTuid(Integer tuid) {
        this.tuid = tuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.bcid
     *
     * @return the value of orders.bcid
     *
     * @mbggenerated
     */
    public Integer getBcid() {
        return bcid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.bcid
     *
     * @param bcid the value for orders.bcid
     *
     * @mbggenerated
     */
    public void setBcid(Integer bcid) {
        this.bcid = bcid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.fsid
     *
     * @return the value of orders.fsid
     *
     * @mbggenerated
     */
    public Integer getFsid() {
        return fsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.fsid
     *
     * @param fsid the value for orders.fsid
     *
     * @mbggenerated
     */
    public void setFsid(Integer fsid) {
        this.fsid = fsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.csid
     *
     * @return the value of orders.csid
     *
     * @mbggenerated
     */
    public Integer getCsid() {
        return csid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.csid
     *
     * @param csid the value for orders.csid
     *
     * @mbggenerated
     */
    public void setCsid(Integer csid) {
        this.csid = csid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.psid
     *
     * @return the value of orders.psid
     *
     * @mbggenerated
     */
    public Integer getPsid() {
        return psid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.psid
     *
     * @param psid the value for orders.psid
     *
     * @mbggenerated
     */
    public void setPsid(Integer psid) {
        this.psid = psid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.piid
     *
     * @return the value of orders.piid
     *
     * @mbggenerated
     */
    public Integer getPiid() {
        return piid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.piid
     *
     * @param piid the value for orders.piid
     *
     * @mbggenerated
     */
    public void setPiid(Integer piid) {
        this.piid = piid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.faid
     *
     * @return the value of orders.faid
     *
     * @mbggenerated
     */
    public Integer getFaid() {
        return faid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.faid
     *
     * @param faid the value for orders.faid
     *
     * @mbggenerated
     */
    public void setFaid(Integer faid) {
        this.faid = faid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.acid
     *
     * @return the value of orders.acid
     *
     * @mbggenerated
     */
    public Integer getAcid() {
        return acid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.acid
     *
     * @param acid the value for orders.acid
     *
     * @mbggenerated
     */
    public void setAcid(Integer acid) {
        this.acid = acid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.heid
     *
     * @return the value of orders.heid
     *
     * @mbggenerated
     */
    public Integer getHeid() {
        return heid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.heid
     *
     * @param heid the value for orders.heid
     *
     * @mbggenerated
     */
    public void setHeid(Integer heid) {
        this.heid = heid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.outid
     *
     * @return the value of orders.outid
     *
     * @mbggenerated
     */
    public Integer getOutid() {
        return outid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.outid
     *
     * @param outid the value for orders.outid
     *
     * @mbggenerated
     */
    public void setOutid(Integer outid) {
        this.outid = outid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.miid
     *
     * @return the value of orders.miid
     *
     * @mbggenerated
     */
    public Integer getMiid() {
        return miid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.miid
     *
     * @param miid the value for orders.miid
     *
     * @mbggenerated
     */
    public void setMiid(Integer miid) {
        this.miid = miid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.toid
     *
     * @return the value of orders.toid
     *
     * @mbggenerated
     */
    public Integer getToid() {
        return toid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.toid
     *
     * @param toid the value for orders.toid
     *
     * @mbggenerated
     */
    public void setToid(Integer toid) {
        this.toid = toid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.slid
     *
     * @return the value of orders.slid
     *
     * @mbggenerated
     */
    public Integer getSlid() {
        return slid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.slid
     *
     * @param slid the value for orders.slid
     *
     * @mbggenerated
     */
    public void setSlid(Integer slid) {
        this.slid = slid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.fpid
     *
     * @return the value of orders.fpid
     *
     * @mbggenerated
     */
    public Integer getFpid() {
        return fpid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.fpid
     *
     * @param fpid the value for orders.fpid
     *
     * @mbggenerated
     */
    public void setFpid(Integer fpid) {
        this.fpid = fpid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.bpid
     *
     * @return the value of orders.bpid
     *
     * @mbggenerated
     */
    public Integer getBpid() {
        return bpid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.bpid
     *
     * @param bpid the value for orders.bpid
     *
     * @mbggenerated
     */
    public void setBpid(Integer bpid) {
        this.bpid = bpid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.chid
     *
     * @return the value of orders.chid
     *
     * @mbggenerated
     */
    public Integer getChid() {
        return chid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.chid
     *
     * @param chid the value for orders.chid
     *
     * @mbggenerated
     */
    public void setChid(Integer chid) {
        this.chid = chid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.fmid
     *
     * @return the value of orders.fmid
     *
     * @mbggenerated
     */
    public Integer getFmid() {
        return fmid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.fmid
     *
     * @param fmid the value for orders.fmid
     *
     * @mbggenerated
     */
    public void setFmid(Integer fmid) {
        this.fmid = fmid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.boid
     *
     * @return the value of orders.boid
     *
     * @mbggenerated
     */
    public Integer getBoid() {
        return boid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.boid
     *
     * @param boid the value for orders.boid
     *
     * @mbggenerated
     */
    public void setBoid(Integer boid) {
        this.boid = boid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.bkid
     *
     * @return the value of orders.bkid
     *
     * @mbggenerated
     */
    public Integer getBkid() {
        return bkid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.bkid
     *
     * @param bkid the value for orders.bkid
     *
     * @mbggenerated
     */
    public void setBkid(Integer bkid) {
        this.bkid = bkid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.mkid
     *
     * @return the value of orders.mkid
     *
     * @mbggenerated
     */
    public Integer getMkid() {
        return mkid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.mkid
     *
     * @param mkid the value for orders.mkid
     *
     * @mbggenerated
     */
    public void setMkid(Integer mkid) {
        this.mkid = mkid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.cuid
     *
     * @return the value of orders.cuid
     *
     * @mbggenerated
     */
    public Integer getCuid() {
        return cuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.cuid
     *
     * @param cuid the value for orders.cuid
     *
     * @mbggenerated
     */
    public void setCuid(Integer cuid) {
        this.cuid = cuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.ncid
     *
     * @return the value of orders.ncid
     *
     * @mbggenerated
     */
    public Integer getNcid() {
        return ncid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.ncid
     *
     * @param ncid the value for orders.ncid
     *
     * @mbggenerated
     */
    public void setNcid(Integer ncid) {
        this.ncid = ncid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.shid
     *
     * @return the value of orders.shid
     *
     * @mbggenerated
     */
    public Integer getShid() {
        return shid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.shid
     *
     * @param shid the value for orders.shid
     *
     * @mbggenerated
     */
    public void setShid(Integer shid) {
        this.shid = shid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.paid
     *
     * @return the value of orders.paid
     *
     * @mbggenerated
     */
    public Integer getPaid() {
        return paid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.paid
     *
     * @param paid the value for orders.paid
     *
     * @mbggenerated
     */
    public void setPaid(Integer paid) {
        this.paid = paid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.exid
     *
     * @return the value of orders.exid
     *
     * @mbggenerated
     */
    public Integer getExid() {
        return exid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.exid
     *
     * @param exid the value for orders.exid
     *
     * @mbggenerated
     */
    public void setExid(Integer exid) {
        this.exid = exid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.payid
     *
     * @return the value of orders.payid
     *
     * @mbggenerated
     */
    public Integer getPayid() {
        return payid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.payid
     *
     * @param payid the value for orders.payid
     *
     * @mbggenerated
     */
    public void setPayid(Integer payid) {
        this.payid = payid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.shiid
     *
     * @return the value of orders.shiid
     *
     * @mbggenerated
     */
    public Integer getShiid() {
        return shiid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.shiid
     *
     * @param shiid the value for orders.shiid
     *
     * @mbggenerated
     */
    public void setShiid(Integer shiid) {
        this.shiid = shiid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", oid=").append(oid);
        sb.append(", cpid=").append(cpid);
        sb.append(", bid=").append(bid);
        sb.append(", ocid=").append(ocid);
        sb.append(", ocode=").append(ocode);
        sb.append(", ophoto=").append(ophoto);
        sb.append(", mlast=").append(mlast);
        sb.append(", etd=").append(etd);
        sb.append(", fsize=").append(fsize);
        sb.append(", onumber=").append(onumber);
        sb.append(", fafactory=").append(fafactory);
        sb.append(", exfactory=").append(exfactory);
        sb.append(", sfactory=").append(sfactory);
        sb.append(", bfactory=").append(bfactory);
        sb.append(", inid=").append(inid);
        sb.append(", ouid=").append(ouid);
        sb.append(", laid=").append(laid);
        sb.append(", prid=").append(prid);
        sb.append(", ofid=").append(ofid);
        sb.append(", said=").append(said);
        sb.append(", tuid=").append(tuid);
        sb.append(", bcid=").append(bcid);
        sb.append(", fsid=").append(fsid);
        sb.append(", csid=").append(csid);
        sb.append(", psid=").append(psid);
        sb.append(", piid=").append(piid);
        sb.append(", faid=").append(faid);
        sb.append(", acid=").append(acid);
        sb.append(", heid=").append(heid);
        sb.append(", outid=").append(outid);
        sb.append(", miid=").append(miid);
        sb.append(", toid=").append(toid);
        sb.append(", slid=").append(slid);
        sb.append(", fpid=").append(fpid);
        sb.append(", bpid=").append(bpid);
        sb.append(", chid=").append(chid);
        sb.append(", fmid=").append(fmid);
        sb.append(", boid=").append(boid);
        sb.append(", bkid=").append(bkid);
        sb.append(", mkid=").append(mkid);
        sb.append(", cuid=").append(cuid);
        sb.append(", ncid=").append(ncid);
        sb.append(", shid=").append(shid);
        sb.append(", paid=").append(paid);
        sb.append(", exid=").append(exid);
        sb.append(", payid=").append(payid);
        sb.append(", shiid=").append(shiid);
        sb.append("]");
        return sb.toString();
    }
}